### ISSUE TITLE
USB Path

### ISSUE THREAD

**Issue by alekslyse** [blakeblackshear/frigate-hass-addons#1]
On the "other" addon for HA it automatically found the coral, and on my home assistant OS I see the devices as

Bus 002 Device 003: ID 18d1:9302
Bus 001 Device 005: ID 8087:0a2b
Bus 001 Device 001: ID 1d6b:0002
Bus 001 Device 007: ID 0951:168e
Bus 001 Device 004: ID 1cf1:0030
Bus 002 Device 001: ID 1d6b:0003
Bus 001 Device 003: ID 0658:0200
Bus 001 Device 006: ID 12d1:1001
Bus 001 Device 002: ID 05e3:0606

From what I know Bus 002 Device 003: ID 18d1:9302 is the google coral. In the setting its set device: device: 'usb:2.3' - or how it it meant to be set?

**Comment by blakeblackshear** [comment]
I am mapping in the USB devices the same way as the other addon, so it should auto detect the same way. Are you sure you don't have multiple frigate addons running? 

That is not the way to set the device, and you only really need to do it if you have multiple corals: https://coral.ai/docs/edgetpu/multiple-edgetpu/#using-the-tensorflow-lite-python-api

**Comment by alekslyse** [comment]
I understood. so usb:0 means first corral usb:1 means second? I just assumed it related to the bus and device id, but setting it to usb:0 it found. Also since im running a nuc it supports renderD128 so hopefully that will give some performance gain too
