### ISSUE TITLE
mqtt client does not connect to internal broker

### ISSUE THREAD

**Issue by BogdanDIA** [blakeblackshear/frigate-hass-addons#102]
Hello,

I am using HA with following versions:
Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

Frigate addon:
Frigate Beta (0.12.0)
Current version: 0.12.0-beta8

HW: RPI4 + EdgeTPU

The problem: I always get the mqtt errors in the logs:

2023-03-03 19:52:48.231974103  [2023-03-03 21:52:48] frigate.comms.mqtt             ERROR   : Unable to publish to stats: client is not connected

The mqtt section in frigate.yml is the following:
mqtt:
  #host: mqtt://core-mosquitto
  host: 192.168.0.140:1883 
  user: mqtt
  password: my_passwd
  topic_prefix: frigate

I tested under ssh mosquitto_pub and mosquitto_sub to check if the credentials are correct and and they are fine. Mqtt is currently used by other plugins without problems. 
mosquitto_pub -L mqtt://mqtt:my_passwd@192.168.0.140:1883:/frigate  -m "abcd"
mosquitto_sub -h 192.168.0.140 -t 'frigate/#'

Any fix for this issue?

Thanks,
Bogdan

**Comment by NickM-27** [comment]
`mqtt://core-mosquitto` is incorrect, you should not be specifying the protocol and it should just be `core-mosquitto`

`192.168.0.140:1883` is also incorrect because the port is a separate field and should not be included in the host field

**Comment by BogdanDIA** [comment]
Thanks for the quick answer. I just tried now the core-mosquitto without the protocol and it works.
Wow, got confused as other addons like Z2M need the protocol.
Also the IP without the port works. Hope this will help others in the future.

Thanks @NickM-27

**Comment by NickM-27** [comment]
@BogdanDIA glad that worked, you should be able to close this issue
