### ISSUE TITLE
Custom go2rtc with Frigate-hass-addon

### ISSUE THREAD

**Issue by Delta1977** [blakeblackshear/frigate-hass-addons#117]
Hi, 
can someone explain me how to use a custom go2rtc bin in combination with the addon?

https://docs.frigate.video/configuration/advanced#custom-go2rtc-version is for addon not very clear

thank you

**Comment by Delta1977** [comment]
i found out by myself.

Maybe you could add a small manual to frigate doku

**Comment by JRascagneres** [comment]
@Delta1977 How did you do this?
