### ISSUE TITLE
Add and expose frigate proxy in HA container installation

### ISSUE THREAD

**Issue by Svyatk0** [blakeblackshear/frigate-hass-addons#119]
Hiya. 
Apologies if this was asked before. 
Any suggestions on manually adding frigate proxy in Home Assistant container? 

My setup is running on truenas and both HA and Frigate run as separate containers. 
It's super useful however to have access to Frigate UI from HA. 
I guess I could try spinning up Frigate  proxy docker and somehow pointing it at HA, but maybe there is a simpler way. 

Any clues would be much appreciated.

**Comment by blakeblackshear** [comment]
I have mostly seen people run home assistant and frigate on separate subdomains behind a reverse proxy. There isn't a good way to expose Frigate in HA with authentication if you aren't using the addon. Some people also just make heavy use of the custom lovelace card within HA as that meets all their needs.

**Comment by Svyatk0** [comment]
Thanks. I will try and make more use of the lovelace card .
