### ISSUE TITLE
Allow custom go2rtc version for frigate addon

### ISSUE THREAD

**Issue by JRascagneres** [blakeblackshear/frigate-hass-addons#123]
I'm looking to move my frigate to my home assistant machine rather than external but require go2rtc 1.5.0 - I don't see a way to utilize a custom version of go2rtc with the addon. Is there some way to do this? Or could we have a configuration option added to allow this?

**Comment by NickM-27** [comment]
This is already supported and in the docs https://docs.frigate.video/configuration/advanced#custom-go2rtc-version

**Comment by JRascagneres** [comment]
Apologies! I expected it to be exposed in a different way. Thanks. I'd like the ability to manually specify paths. I'd much prefer `/config/frigate` folder rather than everything in there.
