### ISSUE TITLE
USB Coral no longer works with Protection Mode enabled

### ISSUE THREAD

**Issue by rfpronk** [blakeblackshear/frigate-hass-addons#14]
Since #13 and the corresponding change in the [supervisor](https://github.com/home-assistant/supervisor/pull/2429/files#diff-9d9b42663129dffdf9ab9475772d2161c835d56d51ba861d73d93e9340980e74R137) I can't get the USB coral working with protection mode enabled. Before I always had this enabled (as is by default) without problems.

I expect the following change to cause this.
[New](https://github.com/home-assistant/supervisor/blob/841e13e29086c3da3d325e35d5f84346386d70db/supervisor/docker/addon.py#L335)
```
volumes.update({"/dev/bus/usb": {"bind": "/dev/bus/usb", "mode": "rw"}})
```
vs [what the Frigate addon specified before](https://github.com/blakeblackshear/frigate-hass-addons/pull/13/files#diff-16128a75ca639145b75f8cbf484f154746f3c3b5b65d5802bab6ed2ad4735d5aL25)
```
    "/dev/bus/usb:/dev/bus/usb:rwm",
```
It's now missing the `mknod` permission on the docker bind for the usb bus.
According to the docker documentation the given mode is ignored when a container runs privileged (which it does when disabling protection mode in the HA supervisor).
Can it be that the Coral stick changes device id upon initialisation makes it to require this extra bit?
Eg the deconz addon still runs fine in protection mode while utilising its zigbee usb stick.

So this might need to be fixed/changed on the supervisor side. It's getting late and I'm getting tired so won't test my theory now. I wanted to create an issue in case someone else ran into the same problem. (okay still diving into it writing this issue but I want to help as I love the product!)

I'm using 
 - HA core-2021.2.2
 - HA supervisor-2021.02.6
 - Frigate Hassio Addon 1.9
 - Running HassOS vmdk on Proxmox with USB passthrough for Coral

### Protection mode enabled
```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.app                    INFO    : Camera processor started for garden: 34
frigate.app                    INFO    : Camera processor started for driveway: 35
frigate.app                    INFO    : Capture process started for garden: 36
detector.coral                 INFO    : Starting detection process: 32
frigate.app                    INFO    : Capture process started for driveway: 37
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.mqtt                   INFO    : MQTT connected
frigate.edgetpu                INFO    : No EdgeTPU detected.
Process detector:coral:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
    delegate = Delegate(library, options)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
    raise ValueError(capture.message)
ValueError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
    object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
  File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
    edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
  File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
    raise ValueError('Failed to load delegate from {}\n{}'.format(
ValueError: Failed to load delegate from libedgetpu.so.1.0
```

### Protection mode disabled
Disable Protection mode for the Frigate addon (don't change anything else) and restart addon.
![Screenshot 2021-02-09 at 23 46 48](https://user-images.githubusercontent.com/19285728/107438655-1b44df00-6b31-11eb-80e9-c28f3c147915.png)

```
 * Starting nginx nginx
   ...done.
frigate.app                    INFO    : Creating directory: /tmp/cache
Starting migrations
peewee_migrate                 INFO    : Starting migrations
There is nothing to migrate
peewee_migrate                 INFO    : There is nothing to migrate
frigate.mqtt                   INFO    : MQTT connected
frigate.app                    INFO    : Camera processor started for garden: 36
frigate.app                    INFO    : Camera processor started for driveway: 37
frigate.app                    INFO    : Capture process started for garden: 39
frigate.app                    INFO    : Capture process started for driveway: 40
detector.coral                 INFO    : Starting detection process: 33
frigate.edgetpu                INFO    : Attempting to load TPU as usb
frigate.edgetpu                INFO    : TPU found
```
And everything works 👍

**Comment by blakeblackshear** [comment]
Thanks for helping track this down.

**Comment by rfpronk** [comment]
I was wrong about the mode. 
[This](https://github.com/home-assistant/supervisor/blob/main/supervisor/hardware/policy.py#L63) is actually the latest code that sets the bind mode for devices.
I did puzzle over lunch and found the solution, creating PR.
