### ISSUE TITLE
Parent Image

### ISSUE THREAD

**Issue by Melkor82** [blakeblackshear/frigate-hass-addons#16]
With the new image 1.10 i still get the 0.8.1 image as seen from portainer in docker that i am unable to remove since i get the error that 0.8.1 has a child image. Both images are 845 MB. I would like to remove the 0.8.1 unused image to save space on my snapshot backups

**Comment by blakeblackshear** [comment]
The docker image has not changed since version 1.6. Every version since 1.6 has used the 0.8.1 frigate image. The updates have been config for the addon only.
