### ISSUE TITLE
Proxy addon issue - when trying to open frigate menu you get 404

### ISSUE THREAD

**Issue by MaBeniu** [blakeblackshear/frigate-hass-addons#166]
I am running frigate 14.0-beta1 via docker-compose.
On a separate container I am running home assistant with frigate proxy addon - version 1.5.
when trying to open frigate from the homeassistant side menu on the left I get frigate new UI loaded but showing 404 error:
![image](https://github.com/blakeblackshear/frigate-hass-addons/assets/107912005/6d0c6edd-8693-4c03-bffa-b8257b49a40e)

If I try to navigate by using new frigate menu all works fine and I can access all the functions. it is just when you navigate between home assistant menus it opens this page with 404 initially.
browser hard reload and empty cache cleanup done, home assistant restarted after installation of beta version.

nginx: log entries when navigating:
![image](https://github.com/blakeblackshear/frigate-hass-addons/assets/107912005/596b5bee-dc08-41f2-8abe-1479b3b74702)

proxy addon config:
```
server: http://192.168.0.181:5000
proxy_pass_host: true
proxy_pass_real_ip: true
```
p.s. new version is really amazing I am thriled how nice that is!!!!!!!!!!!!!!!!!!!!!!!!! super amazing job guys!!

**Comment by DieMetRik** [comment]
Same here. Wait for fix

**Comment by MaBeniu** [comment]
Confirm with 14.beta2 fixed.
