### ISSUE TITLE
dead frigate plugin

### ISSUE THREAD

**Issue by emilianogetino** [blakeblackshear/frigate-hass-addons#175]
Hello, if someone can guide me a little, I'm very lost, let me explain.
I have a HassOS installation on a minipc, the frigate plugin does not work, after months of working perfectly with 10 cameras, it seems to have died since the 8th, which are the last recordings.
I hit stop and instead of exiting down start it continues to exit stop and restart and the CPU usage is at 24%.
If I restart, with the boot option disabled, the plugin screen shows the same thing, as if it were booted and with 24% CPU.
If I uninstall the plugin and reinstall, whether I install the fullaccess version that is the one I had, or if I install the normal one, everything remains the same.
After all this, if I look at the Friguete registry before reinstalling, it was frozen, the last entry was from the 12th I think, now it is empty.
The fact is that I don't see any related errors, if I open the frigate integration it tells me that the plugin is not ready and it may still be starting.
In the system log I only see errors:
Error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats: Cannot connect to host ccab4aaf-frigate-fa:5000 ssl:default [None]
It must be that the integration does not connect to the plugin.
The last test was to restore the plugin from a previous copy, but it didn't solve anything.
I totally don't know what to do, any guidance on where to go would be appreciated.

**Comment by NickM-27** [comment]
I'd suggest restarting HA OS, sounds like something got stuck on that side of things

**Comment by emilianogetino** [comment]
Every time I change something or reinstall the plugin I restart homeassistant, I have restarted it more than a dozen times, but nothing changes.
The plugin registry is empty and when trying to open the web interface it says that the plugin appears not to be started.
I don't know where to get some more debugging information that allows you to see what is happening.
thanks for your help.

**Comment by NickM-27** [comment]
when you say restart home assistant, where are you doing this from? there is a difference between restarting home assistant core and restarting the entire OS.

**Comment by emilianogetino** [comment]
![Screenshot_2024-07-15-17-34-09-601_io homeassistant companion android](https://github.com/user-attachments/assets/65e8cb99-7155-474d-93fb-a3fc5568c1ad)

**Comment by emilianogetino** [comment]
![IMG_20240715_173829](https://github.com/user-attachments/assets/d3894f67-cf23-4b15-aee7-bfca21de0121)

**Comment by NickM-27** [comment]
yes, that only restarts home assistant core, not the full OS

**Comment by emilianogetino** [comment]
Solved 8), thank youssss.
Indeed, a complete reset had to be done, everything seems to be back in its place.
All the best.

**Comment by NickM-27** [comment]
great, you can close this issue then 👍
