### ISSUE TITLE
Beta addon updated to stable

### ISSUE THREAD

**Issue by Morphy99** [blakeblackshear/frigate-hass-addons#181]
As the Beta Addon was updated to the stable image, removing the beta results in this error when trying to start stable:
`Image ghcr.io/blakeblackshear/frigate:0.14.0 does not exist for addon_ccab4aaf_frigate-fa`

I had to remove both and reinstall. I'm not sure why the beta was updated to the same image as the stable. This could also cause issues in the future when the new beta is started and a user has auto update on...

**Comment by NickM-27** [comment]
What do you mean? If the beta image isn't updated then users wouldn't be on the latest version. Updating the image used for the beta won't cause any issues as users can stay on it indefinitely. We will always be disabling auto update for the addons

**Comment by Morphy99** [comment]
I get that they wouldn't be on the latest version but it's caused issues with how HA OS has managed the same image with both add-ons. I don't want to jump on the latest beta of 0.15 so have gone back to the stable add-on. Removing the beta addon caused the image for both to be deleted.

**Comment by NickM-27** [comment]
right, the flip side of that is that users want to just stay on the beta addon and not deal with having to reconfigure the integration every time. Once 0.14.1 comes out the beta and stable addons will be updated again.

in general, this is a bug in HA supervisor if multiple images point to the same image

**Comment by Morphy99** [comment]
Sure. I'm not debating what users will do going forward. It's just unusual for a beta channel to be using stable images and it's caused a bug in the HA addon system.

**Comment by NickM-27** [comment]
I disagree though, for example the home assistant `beta` tag always gets updated to the stable versions

**Comment by Morphy99** [comment]
https://github.com/home-assistant/supervisor/issues/5244
