### ISSUE TITLE
coral TPU not detected after upgrade to v0.14.0

### ISSUE THREAD

**Issue by Matthiasfranck** [blakeblackshear/frigate-hass-addons#183]
I use frigate full access in HAS. After upgrading from 0.13.2 to 0.14.0, my coral edge TPU is not detected anymore.

The issue looks very similar to https://github.com/blakeblackshear/frigate/issues/3890

I downgraded frigate using a HAS backup and everything started to work as normal.

I want to share this as people are probably not yet aware of the issue.

**Comment by NickM-27** [comment]
nothing changed in terms of how the coral is interacted with, another user posted something similar and it was because they forgot to disable protected mode and they were using the full access addon

**Comment by StefanTT** [comment]
I am also fighting with this problem.

Home-Assistant with the Frigate addon freshly installed, version 0.14.1.
Disabled protected mode.

The detector configuration is like this:
```
detectors:
  coral:
    type: edgetpu
    device: usb
```

TPU is not detected and Frigate stops.

Running frigate on the same machine in an LXC container worked for months now, so the TPU is reachable and working. Yes I stopped the LXC container.

**Comment by Matthiasfranck** [comment]
I was also running without protected mode.

**Comment by Matthiasfranck** [comment]
I have a zwave and zigbee dongle attached. I can however use a powered usb hub to plug the tpu in.

Anyway it is still strange that it only happens when updating to newer version.

**Comment by StefanTT** [comment]
The update might have changed how Frigate interacts with the TPU on startup, drawing a bit more power now on start. I did some testing. All works fine when I unplug bluetooth and thread on boot and plug them in later. I will use a powered hub for the two sticks as the TPU is inside the server.

**Comment by Matthiasfranck** [comment]
@NickM-27 wrote
> nothing changed in terms of how the coral is interacted with

But ok, I will test it later again. I have an usb coral, so only thing I can do is use powered USB hub and add my zigbee, zwave and coral to it.

**Comment by tung256** [comment]
@Matthiasfranck it's a shame there is no way to revert to a older versions. i updated from v12 to v14 and instantly regretted.  i do have a hard drive back up with v12 and HA OS, but that was almost 2 years ago.  a lot of things have changed in my house since then.

**Comment by Matthiasfranck** [comment]
Hi, I just confirmed. I need a powered USB hub when updating to frigate 14.x. Then the TPU is correctly detected.

I see however some other issue with increased CPU usage.
