### ISSUE TITLE
Default db path /config/frigate.db lead to improper backup structure and size 

### ISSUE THREAD

**Issue by palinf** [blakeblackshear/frigate-hass-addons#184]
Default backup is /config/frigate.db

This means than when doing partial or full backup including homeassistant then homeassistant will be embedding frigate.db

Since there is little interest of the db without clips I would recommend '/media/frigate/frigate.db' as a default db.

**Comment by NickM-27** [comment]
It used to be /media, but many users user a separate NAS for their media and sqlite does not work well on network volumes 

As a user you can change the location in the config if you want to, this is working as intended
