### ISSUE TITLE
Generate a frigate addon version with default LIBVA_DRIVER_NAME=radeonsi

### ISSUE THREAD

**Issue by SoulSlayerPT** [blakeblackshear/frigate-hass-addons#27]
Hello,

I am trying to use the hassio addon with the LIBVA_DRIVER_NAME=radeonsi so i can use my ryzen iGPU.

I try to change the addon container with portainer, but every time i restart the addon, it restores the original value.

How do i change the addon to default to env LIBVA_DRIVER_NAME=radeonsi?

Can you add a way to change the default LIBVA_DRIVER_NAME?

Thank you.

**Comment by blakeblackshear** [comment]
You can set environment variables in the config file already.

**Comment by SoulSlayerPT** [comment]
Sorry. How? In the config.json file in the addon?

**Comment by blakeblackshear** [comment]
https://blakeblackshear.github.io/frigate/configuration/advanced#environment_vars

**Comment by SoulSlayerPT** [comment]
Wow, sorry my bad didn't know this was possible.

Thank you very much!
