### ISSUE TITLE
core-2021.8.3 caused error at startup

### ISSUE THREAD

**Issue by sys1aeg** [blakeblackshear/frigate-hass-addons#30]
message from log:
Logger: homeassistant.setup
Source: setup.py:173
First occurred: 8:20:39 PM (1 occurrences)
Last logged: 8:20:39 PM

Setup failed for frigate: Unable to import component: cannot import name 'Message' from 'homeassistant.components.mqtt.models' (/usr/src/homeassistant/homeassistant/components/mqtt/models.py)

**Comment by blakeblackshear** [comment]
You need to use the latest version of the integration.

**Comment by sys1aeg** [comment]
I am running 1.13 
where is the latest version ?

**Comment by sys1aeg** [comment]
ok think i have it !
installed integration component with hacs
