### ISSUE TITLE
proxy add on install fails

### ISSUE THREAD

**Issue by danuals** [blakeblackshear/frigate-hass-addons#39]
fails to install with this error

`The command '/bin/bash -o pipefail -c apk add --no-cache nginx=1.20.1-r3 && rm -f -r /etc/nginx /opt/build /opt/index.html /opt/package.sh /opt/src /opt/static /opt/stylesheets /opt/.[!.]* /opt/*.md /opt/nodemon.json /opt/kustomization.yaml /opt/kubernetes /opt/docker /opt/docs /root/.cache /root/.config /root/.npmrc /root/.node-gyp /root/.npm /tmp/.[!.]* /tmp/* /usr/lib/node_modules /usr/local/share/.cache' returned a non-zero code: 1`

**Comment by danuals** [comment]
proxmos install, with frigate 9.0.0 rc4 in a separate lxc container

2.0 integration running ok

HA supervisor-2021.09.0
core-2021.9.7
Home Assistant OS 6.4

**Comment by michelebossa** [comment]
I have the same issue i suppose it is a problem on this package.

![image](https://user-images.githubusercontent.com/38975058/134512762-efc5ef4d-f6bf-4706-b41f-6e4d79fd3ccc.png)

**Comment by Ixian** [comment]
I've successfully installed this on an RPI4; I think that package source is dynamic depending on platform. 

This might be more related to temporary DNS/network issues as  michelebossa notes.

**Comment by blakeblackshear** [comment]
What hardware/os are you installing this on?

**Comment by danuals** [comment]
Intel NUC7PJYH
Proxmox 6-.4-13

**Comment by danuals** [comment]
Has os is in a lvm
Frigate 9 is in  seperate lxc

**Comment by michelebossa** [comment]
I'm thinking it was a general problem  i have tried to install another addon but i recive a message similar.

![image](https://user-images.githubusercontent.com/38975058/134641830-5e21ec4a-163e-4fb3-8596-b87d83a0537d.png)

There is maybe a DNS issue i have tried to set the DNS into HA but the problem persist.

![image](https://user-images.githubusercontent.com/38975058/134642280-d61a6a0c-4859-4996-aa06-fd7275b80429.png)

I have no idea how fix the problem

**Comment by michelebossa** [comment]
Hi @blakeblackshear,
i have found a solution by following these issue on alpine git https://github.com/alpinelinux/docker-alpine/issues/98
I have made a local copy and added the row `RUN sed -i 's/https/http/' /etc/apk/repositories`

![image](https://user-images.githubusercontent.com/38975058/134646598-ceb5ee46-8b8a-4db5-96c4-6c05f2801dbf.png)

It is possible to add these into Dockerfile?
Thanks

**Comment by danuals** [comment]
So the nginx proxy manager could be what’s messing this up?

**Comment by michelebossa** [comment]
The issue alpinelinux/docker-alpine#98 spoke about a problem under https of dl-cdn.alpinelinux.org in some circumstances i don't think it is a nginx fault.

The row of code can force to use http insted https douring packages download.

**Comment by danuals** [comment]
> Hi @blakeblackshear,
> i have found a solution by following these issue on alpine git [alpinelinux/docker-alpine#98](https://github.com/alpinelinux/docker-alpine/issues/98)
> I have made a local copy and added the row `RUN sed -i 's/https/http/' /etc/apk/repositories`
> 
> ![image](https://user-images.githubusercontent.com/38975058/134646598-ceb5ee46-8b8a-4db5-96c4-6c05f2801dbf.png)
> 
> It is possible to add these into Dockerfile?
> Thanks

still fails with this added to my docker file, mine is a different issue to yours?


`The command '/bin/bash -o pipefail -c apk add --no-cache nginx=1.20.1-r3 && rm -f -r /etc/nginx /opt/build /opt/index.html /opt/package.sh /opt/src /opt/static /opt/stylesheets /opt/.[!.]* /opt/*.md /opt/nodemon.json /opt/kustomization.yaml /opt/kubernetes /opt/docker /opt/docs /root/.cache /root/.config /root/.npmrc /root/.node-gyp /root/.npm /tmp/.[!.]* /tmp/* /usr/lib/node_modules /usr/local/share/.cache' returned a non-zero code: 1`

**Comment by michelebossa** [comment]
Are you sure to select the local installation of addon? Are you copied the repo in your local folder and edit the docker file?( check the row to add before to run commadn)

**Comment by danuals** [comment]
<img width="669" alt="Screenshot 2021-09-26 at 19 41 44" src="https://user-images.githubusercontent.com/63956367/134820182-f37814bc-8cdf-44d5-a676-379486d20611.png">

**Comment by michelebossa** [comment]
This part it is ok.. please check il you select under supervisior the local addon and istall it
![Screenshot_20210926-204649_Home Assistant.jpg](https://user-images.githubusercontent.com/38975058/134820344-2e2960ca-4bb3-49c8-b89b-0f6e2efec896.jpg)

Last check into supervision log i recived some message with https and no permission 

![Screenshot_20210926-204704_Home Assistant.jpg](https://user-images.githubusercontent.com/38975058/134820375-20c4a432-8b99-4332-9c70-85c72266476d.jpg)

**Comment by danuals** [comment]
`21-09-26 19:55:44 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build local/amd64-addon-frigate-proxy:1.1: The command '/bin/bash -o pipefail -c apk add --no-cache         nginx=1.20.1-r3     && rm -f -r         /etc/nginx         /opt/build         /opt/index.html         /opt/package.sh         /opt/src         /opt/static         /opt/stylesheets         /opt/.[!.]*         /opt/*.md         /opt/nodemon.json         /opt/kustomization.yaml         /opt/kubernetes         /opt/docker         /opt/docs         /root/.cache         /root/.config         /root/.npmrc         /root/.node-gyp         /root/.npm         /tmp/.[!.]*         /tmp/*         /usr/lib/node_modules         /usr/local/share/.cache' returned a non-zero code: 1
21-09-26 19:55:44 ERROR (SyncWorker_1) [supervisor.docker.addon] Build log: 
Step 1/20 : ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:10.0.1
Step 2/20 : FROM ${BUILD_FROM}
 ---> 8ae976d039fd
Step 3/20 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> f7349fbd9c72
Step 4/20 : RUN sed -i 's/https/http/' /etc/apk/repositories
 ---> Using cache
 ---> 7f2660d1ec33
Step 5/20 : RUN     apk add --no-cache         nginx=1.20.1-r3     && rm -f -r         /etc/nginx         /opt/build         /opt/index.html         /opt/package.sh         /opt/src         /opt/static         /opt/stylesheets         /opt/.[!.]*         /opt/*.md         /opt/nodemon.json         /opt/kustomization.yaml         /opt/kubernetes         /opt/docker         /opt/docs         /root/.cache         /root/.config         /root/.npmrc         /root/.node-gyp         /root/.npm         /tmp/.[!.]*         /tmp/*         /usr/lib/node_modules         /usr/local/share/.cache
 ---> Running in 722a6c001463
fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
WARNING: 
Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later)


fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
WARNING: 
Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later)


ERROR: 
unable to select packages:


  nginx (no such package):
    required by: world[nginx=1.20.1-r3]
Removing intermediate container 722a6c001463
`

**Comment by danuals** [comment]
stock add on

`21-09-26 20:08:30 ERROR (SyncWorker_3) [supervisor.docker.addon] Can't build ccab4aaf/amd64-addon-frigate-proxy:1.1: The command '/bin/bash -o pipefail -c apk add --no-cache         nginx=1.20.1-r3     && rm -f -r         /etc/nginx         /opt/build         /opt/index.html         /opt/package.sh         /opt/src         /opt/static         /opt/stylesheets         /opt/.[!.]*         /opt/*.md         /opt/nodemon.json         /opt/kustomization.yaml         /opt/kubernetes         /opt/docker         /opt/docs         /root/.cache         /root/.config         /root/.npmrc         /root/.node-gyp         /root/.npm         /tmp/.[!.]*         /tmp/*         /usr/lib/node_modules         /usr/local/share/.cache' returned a non-zero code: 1
21-09-26 20:08:30 ERROR (SyncWorker_3) [supervisor.docker.addon] Build log: 
Step 1/19 : ARG BUILD_FROM=ghcr.io/hassio-addons/base/amd64:10.0.1
Step 2/19 : FROM ${BUILD_FROM}
 ---> 8ae976d039fd
Step 3/19 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> f7349fbd9c72
Step 4/19 : RUN     apk add --no-cache         nginx=1.20.1-r3     && rm -f -r         /etc/nginx         /opt/build         /opt/index.html         /opt/package.sh         /opt/src         /opt/static         /opt/stylesheets         /opt/.[!.]*         /opt/*.md         /opt/nodemon.json         /opt/kustomization.yaml         /opt/kubernetes         /opt/docker         /opt/docs         /root/.cache         /root/.config         /root/.npmrc         /root/.node-gyp         /root/.npm         /tmp/.[!.]*         /tmp/*         /usr/lib/node_modules         /usr/local/share/.cache
 ---> Running in 5e1ff46fafb0
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
WARNING: 
Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later)


ERROR: unable to select packages:


  nginx (no such package):
    required by: world[nginx=1.20.1-r3]
Removing intermediate container 5e1ff46fafb0
`

**Comment by michelebossa** [comment]
Bad stuff!! I have no idea sorry

**Comment by blakeblackshear** [comment]
I will probably just switch this to the debian base to avoid alpine related issues altogether.

**Comment by blakeblackshear** [comment]
Just pushed a new version. Give that a try.

**Comment by danuals** [comment]
Still fails, add on page error-
`The command '/bin/bash -o pipefail -c apt-get -qq update && apt-get -qq install --no-install-recommends -y nginx && (apt-get autoremove -y; apt-get autoclean -y)' returned a non-zero code: 100 `

supervisor error-


`21-09-27 06:38:00 INFO (SyncWorker_5) [supervisor.docker.addon] Starting build for ccab4aaf/amd64-addon-frigate-proxy:1.2
21-09-27 06:38:56 ERROR (SyncWorker_5) [supervisor.docker.addon] Can't build ccab4aaf/amd64-addon-frigate-proxy:1.2: The command '/bin/bash -o pipefail -c apt-get -qq update     && apt-get -qq install --no-install-recommends -y nginx     && (apt-get autoremove -y; apt-get autoclean -y)' returned a non-zero code: 100
21-09-27 06:38:56 ERROR (SyncWorker_5) [supervisor.docker.addon] Build log: 
Step 1/19 : ARG BUILD_ARCH
Step 2/19 : FROM ghcr.io/hassio-addons/debian-base/${BUILD_ARCH}:5.1.0
 ---> 63ca583608d8
Step 3/19 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Running in e9293a6885cf
Removing intermediate container e9293a6885cf
 ---> 547d21b65a63
Step 4/19 : RUN apt-get -qq update     && apt-get -qq install --no-install-recommends -y nginx     && (apt-get autoremove -y; apt-get autoclean -y)
 ---> Running in dbb0a020e60f
W
: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'


W
: 
Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'security.debian.org'


W
: 
Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'


W
: 
Some index files failed to download. They have been ignored, or old ones used instead.


E: 
Unable to locate package nginx


Removing intermediate container dbb0a020e60f
`

**Comment by danuals** [comment]
has to be an error on my end, re booting host and I'll keep trying

**Comment by danuals** [comment]
Still the same. 
Other add ons are installing fine including frigate beta 0.9.0

**Comment by michelebossa** [comment]
@danuals  yesterday i have updated the libseccomp2 and now i think all my problem are gone. 


`# Get signing keys to verify the new packages, otherwise they will not install
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138

# Add the Buster backport repository to apt sources.list
$ echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list

$ sudo apt update
$ sudo apt install libseccomp2 -t buster-backports`
Url of discussion 
https://community.home-assistant.io/t/supervisor-cant-install-add-ons/301771/15

mybe you can try

**Comment by danuals** [comment]
Mine is a HAassOS install on proxmox. 

What’s your install?

**Comment by michelebossa** [comment]
I have Raspbian GNU/Linux 10 (buster)

**Comment by danuals** [comment]
Different install, direct hassOS install has no access to apt-get.

**Comment by danuals** [comment]
Ahhhhhhhh, found it. Dns setting in HA supervisor had old address. Testing now…..

**Comment by danuals** [comment]
Both versions now install fine. 👍🏼

Sorry @blakeblackshear
