### ISSUE TITLE
How To Run Proxy Locally

### ISSUE THREAD

**Issue by mitchross** [blakeblackshear/frigate-hass-addons#41]
Is there setup / dev instructions for running https://github.com/blakeblackshear/frigate-hass-addons/tree/main/frigate_proxy locally?

**Comment by blakeblackshear** [comment]
For development, I use the devcontainer. It's a very simple addon. Just an nginx install with a simple proxy config.

**Comment by mitchross** [comment]
Can I "access" it via browser? Do I have to change any configs? Or is it hard tied to hassio ? thanks

**Comment by blakeblackshear** [comment]
Home assistant ingress routes the traffic. I don't think you can access it without going through ingress, but the entire nginx config is right there if you want to create an nginx config based on it to see if it will work behind cloudflare.
