### ISSUE TITLE
Frigate NVR Proxy Port 5000

### ISSUE THREAD

**Issue by justynbell** [blakeblackshear/frigate-hass-addons#58]
Today I uninstalled the HA Frigate addon, and installed Frigate via Docker on a HA Supervised setup.  Everything worked well, I can reach the standalone Frigate interface at \<my-ip\>:5000.

However, when I tried to install the Frigate NVR Proxy in HA to be able to reach the Frigate interface from the HA sidebar, I get the following error:

![image](https://user-images.githubusercontent.com/5696464/147184635-50dc0748-4319-4591-a2e7-9812a9d362fb.png)

Yeah, port 5000 is being used by the standalone Frigate instance.  If I stop the Docker Frigate instance, I'm able to start the Proxy integration but obviously nothing shows up.

It feels like I'm missing something really stupid, but I'm not able to really find any documentation on the Proxy addon, and only one other ticket that where the solution was to completely power down his Raspberry Pi, which isn't applicable here.

This is the configuration (I also tried frigate.local for options->server, but that yields the same results)
![image](https://user-images.githubusercontent.com/5696464/147184789-eb1baa44-2f6f-4dd7-b902-9b5879890942.png)

This is the log from HA itself:

> 21-12-22 19:37:57 ERROR (SyncWorker_4) [supervisor.docker] Can't start addon_ccab4aaf_frigate-proxy: 500 Server Error for http+docker://localhost/v1.41/containers/4a0cb64213188eaf8ce3e569727705bdefc09540c6ce993efc1a266e4568c15c/start: Internal Server Error ("driver failed programming external connectivity on endpoint addon_ccab4aaf_frigate-proxy (b27d5e440f2edea44907f55e93c75a9de1ac702f9e6751b66a028e6af5137380): Bind for 0.0.0.0:5000 failed: port is already allocated")

**Comment by blakeblackshear** [comment]
Try changing the port on the configuration tab to something other than 5000

**Comment by justynbell** [comment]
Yep, I knew it was something stupid.

The "Options" panel makes sense, but could you give a quick blurb on what the "Network" panel is used for?  The NVR Proxy addon is specifically for linking a standalone install into HA, so I'm not sure what "Web interface" it's talking about.

**Comment by blakeblackshear** [comment]
It will expose Frigate's UI on that port from the HassOS ip address too. Probably not necessary.

**Comment by justynbell** [comment]
Okay, that makes sense.
I know you get this a lot but thanks for the great NVR software.
