### ISSUE TITLE
[FR] tmpfs support for add-on

### ISSUE THREAD

**Issue by msekoranja** [blakeblackshear/frigate-hass-addons#6]
As documented for the frigate docker image, a tmpfs is a great solution for cache.
However, HA add-on does not have this implemented. 
Running this on rPI 4 (w/ 8GB of RAM) on USB I have plenty of free RAM and a bit worried about USB longevity. Some are even using microSD(!).

Without implementing this inside of the add-on Docker image (i.e. creating tmpfs inside) the HA add-on
infrastructure already supports tmpfs. Simply adding one line to config.json and set cache_dir to proper location does the trick
```
+  "tmpfs": "size=512m,rw",
```
``` 
+     "cache_dir": "/tmpfs"
```

One would wish to make tmpfs size configurable (or disabled) via add-on configuration. I think is can only be achieved within add-on docker image (add-on configuration + S6 overlay init scripts). No hard to do. If not already done/planned, I can try to implement this.

**Comment by blakeblackshear** [comment]
I have not implemented this. Cache location for next version will be fixed at /tmp/cache.

**Comment by msekoranja** [comment]
I have checked frigate Docker images and I do not like the idea of adding HA specific packages to frigate image nor adding complexity to add-on image. 
The simple solution is to add support to frigate via its config file. I all make a pull request and the you to decide if this is a good idea, etc.
