### ISSUE TITLE
Invalid Add-on repository!

### ISSUE THREAD

**Issue by arthur-morgan-1** [blakeblackshear/frigate-hass-addons#60]
Getting "Invalid Add-on repository!" message when trying to add the URL to the Add-on Store

**Comment by SamMousa** [comment]
Check that you did not copy the `. ` at the end of the sentence in the readme. It is not part of the URL.

**Comment by larsreinhardt** [comment]
Had the same issue. Reloaded the page and it loaded. Unknown why
