### ISSUE TITLE
Is it possible to access Frigate Docker Container instance via Home Assistant (via a proxy) (not addon)

### ISSUE THREAD

**Issue by LaurenceGough** [blakeblackshear/frigate-hass-addons#74]
Hello,

I redone my whole setup over the last couple of days so I can run the latest Frigate Beta, I'm now using Docker containers for both Home Assistant and Frigate NVR. A painful process I don't wish to repeat ha...

Something I didn't realise was that the Frigate Proxy appears to be only available as an addon for Home Assistant supervised or HAOS. Are people running this as a Docker container somehow?

This means currently we cannot access Frigate outside of our home network, unless I'm doing something wrong?

As this is the recommended install method, how are people accessing it from outside their house?

Or is everyone just using a VPN, I'd rather not..

Thanks,

Laurence

**Comment by monocycler** [comment]
I was about to do what Laurence did but also foresaw this impending issue. Is there a solution to having Docker containers for both Home Assistant and Frigate NVR and yet having Frigate in the left-hand menu and accessible via Nabu Casa cloud?

**Comment by jean-paullizotte** [comment]
I'm running both as containers and can generally access the streams as cameras, clips and snapshots in the media catalog of HA.
I've even got node red sending notifications to my phone with previews. All working because my HA is available via the net.
I'm not sure what else you would need.

**Comment by LaurenceGough** [comment]
Linking Frigate standalone to Home assistant never worked well for me. The UI isn't as good and it wasn't as responsive or as reliable. 

What has worked absolutely amazingly is setting up a Cloudflare zero trust tunnel. I would highly recommend this to anyone.
