### ISSUE TITLE
Coral USB issue

### ISSUE THREAD

**Issue by mserrar** [blakeblackshear/frigate-hass-addons#77]
Hi,
I plugged my new USB Coral, when I start frigate I get the message: No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors

It doesn't seem to be able to find the USB. I am not using a VM.
Thank you.

**Comment by NickM-27** [comment]
> I am not using a VM.

Meaning you flashed HA OS to a device?

What are you running on?

**Comment by mserrar** [comment]
Yeah I am running HA OS on a NUC.

**Comment by mserrar** [comment]
Thank you. Changing the cable worked for me.

**Comment by NickM-27** [comment]
> Thank you. Changing the cable worked for me.

Glad it worked, you should be good to close this issue now
