### ISSUE TITLE
Errno 113: No route to host

### ISSUE THREAD

**Issue by lreynolds188** [blakeblackshear/frigate-hass-addons#96]
I've followed the guide [here](https://smarthomepursuits.com/how-to-install-frigate-in-home-assistant-for-pt1/) and managed to get Mosquitto setup and functioning. I've installed the Frigate addon but cannot seem to get it to start correctly.

### Frigate Log
![Screenshot_20230123_171018](https://user-images.githubusercontent.com/17304215/213983593-2daef9f1-ef41-4464-9c27-b311eddf27dd.png)

### Frigate.yml
![Screenshot_20230123_171212](https://user-images.githubusercontent.com/17304215/213983780-cc7273ad-29e5-41f9-8269-b5c643e206a9.png)

**Comment by blakeblackshear** [comment]
Looks like your mqtt host is wrong.

**Comment by lreynolds188** [comment]
Correct you are. I had manually misconfigured mqtt in hassos. Thanks for the help and sorry for the inaccurate issue.
